version: '3.1'

services:

  mongo:
    image: mongo:4.4.14-focal
    restart: always
    ports:
        - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: spring
      MONGO_INITDB_ROOT_PASSWORD: 1234
